### ISSUE TITLE
Cannot get to main interface

### ISSUE THREAD

**Issue by alyms108** [Quacky2200/Spotify-Web-Player-for-Linux#79] opened 2017-03-02 22:37 UTC
I'm currently running Linux Mint 17.3, MATE edition on a white unibody Macbook. I recently installed the webplayer and was able to sign in after completing the captcha challenge. However, the next screen I got to just had the spotify logo on it with a green button saying Log in with Spotify. I click on the the button, and another window seems to open but disappears just as quickly. Nothing else happens. This makes the app unusable.

![image](https://cloud.githubusercontent.com/assets/10800186/23530234/77bb3436-ff66-11e6-835e-e3ee799175c3.png)

**Comment by Quacky2200** [comment] 2017-03-03 20:03
Duplicate of #67

**Comment by Quacky2200** [comment] 2017-04-21 22:23
A new fix for anyone who may want to continue to use my application has been applied in commit b325d4c391f9d1e8749b71c16290433837625173. A new release ASAP.

**Closed by Quacky2200** 2017-04-21 22:23 UTC
Labels: duplicate
