### ISSUE TITLE
Packaging is broken

### ISSUE THREAD

**Issue by probonopd** [Quacky2200/Spotify-Web-Player-for-Linux#25] opened 2016-09-28 05:26 UTC
Packaging is utterly broken; please consider using [electron-builder](https://github.com/electron-userland/electron-builder).

**Comment by Quacky2200** [comment] 2016-09-28 06:15
Can you please explain what is broken so I can see what's wrong and perhaps offer a solution rather than blindly redirecting me to an electron-builder?

For instance, OS used, how you installed, did it install, the problem you're facing, does it open, what happens if it does, etc, etc???

**Comment by probonopd** [comment] 2016-09-28 07:25
I am trying to build an [AppImage](http://appimage.org/) from the deb, and in the process I see that the deb is violating many of the conventions that debian packages normally follow. I will give some examples below. My use case might not be a typical one; but I am sure that if you'd want to get your deb into debian, for example, you'd have to do many changes. I know from first-hand experience how cumbersome it is to make a deb that would meet debian's strict requirements so I am not suggesting that you should necessarily do so. 

* Application icons don't belong into `/usr/bin/spotifywebplayer/icons`
* Dependencies need to be specified in the deb so that apt can install them at deb installation time and not in a script `usr/bin/spotifywebplayer/get_prerequisites.sh`. ALternatively, they should be bundled inside the deb (although debian wouldn't accept this)
* The main executable is expected in `/usr/bin/spotifywebplayer` and not in `/usr/bin/spotifywebplayer/spotifywebplayer`
* Be careful about the icon, might be non-free

**Comment by Quacky2200** [comment] 2016-09-28 08:00
A quick response: 

- The icon is actually put into `/usr/share/pixmaps` , `/usr/bin/spotifywebplayer/icons` are mostly for the project/tray icons. 

- The listian output has far more conventions that my deb doesn't follow but enough so that it can be installed

- I do not want Node.js and Electron to be installed unnecessarily, technically it should only use Electron but sadly the D-Bus dependencies require Node.js rather than libnode.so as some kind of library in libnode.so is different and D-Bus libraries fail.

- I could put spotifywebplayer script executable into /usr/bin I just never did at the time and have never done

- Yes, the icon might be non-free from Spotify but the icon is still installed by a normal Spotify client, also, this player is a representation of the service and implementation, not an imitation/copy of their service. I cannot rename Spotify Web Player for Linux as it is Spotify Web Player that I'm just re-encapsulating

- I would make alternative packages if they were easy but it seems debian and rpm makes it too complicated to allow a developer to make a package without following so many different protocols that aren't always documented well. 

- Permissions and a few other lintian requirements aren't there, I don't exactly have the time to make sure it conforms to all their protocols and to make sure it just works and installs

**Comment by Quacky2200** [comment] 2016-09-29 10:05
Could these make_deb.sh changes help make AppImage easier?

- Prevent lib folder being removed so that the debian package contains Electron and Node.js (I don't see how it couldn't be allowed? - as such, the debian package we would be creating here would just be for an AppImage)

- Copy `spotifywebplayer` in `/usr/bin` for the debian package

**Comment by probonopd** [comment] 2016-09-29 12:07
Yes, but the main point is that the deb should specify the dependencies so that ´get_prerequisites.sh´ would no longer be needed.

**Comment by Quacky2200** [comment] 2016-09-29 12:51
Well the file can always be removed, Electron could be just made as a NPM module and Node.js a dependency. but the Electron executable needs to be changed to the app name

**Comment by Quacky2200** [comment] 2016-11-11 06:19
I have been able to create a AppImage and Deb after my recent commit and a few changes yet to be uploaded, however, I'm having a problem with AppImage and electron-builder. I have tried to follow this GitHub [issue](https://github.com/electron-userland/electron-builder/issues#644) to solve my problem, but I have been unable to make pepperflash work successfully. I am able to use flash without the builder, I just need to successfully implement it.

I have looked at the location and they are fine, I'm pretty sure Electron is loading the plugin, at least from what I think I can see from `navigator.plugins`.

As soon as these are quickly fixed, I will be able to produce AppImages, and hopefully later, snaps.

**Comment by probonopd** [comment] 2016-11-11 07:10
@develaer?

**Comment by develar** [comment] 2016-11-11 07:46
@Quacky2200 What problem do you have? How I can reproduce it and help? I see that "a few changes yet to be uploaded" so, I guess, it is not yet pushed and I cannot simply clone your repo to investigate?

**Comment by develar** [comment] 2016-11-11 07:47
> and hopefully later, snaps.

Your PR to electron-builder is welcome ;)

**Comment by Quacky2200** [comment] 2016-11-11 07:56
Do you mind if I were to just put it all in a ZIP for you to diagnose? I wouldn't say it's that much more different than the latest commit, it just has the start of my build towards AppImage using the build folder, with my icon inside and the 2 package.json's describing a very basic setup

**Comment by develar** [comment] 2016-11-11 07:58
> Do you mind if I were to just put it all in a ZIP for you to diagnose?

No, it is ok.

**Comment by Quacky2200** [comment] 2016-11-11 08:07
Ok, well this is my package JSON setup

app
```
{
  "name": "spotifywebplayer",
  "productName": "Spotify Web Player",
  "version": "1.0.25",
  "description": "An Electron wrapper of Spotify Web Player to increase desktop integration for a stable Spotify Player for Linux replacement",
  "main": "app.js",
  "scripts": {
    "start": "electron app.js",
    "":""
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron/electron-quick-start.git"
  },
  "keywords": [
    "play",
    "music"
  ],
  "author": {
    "name": "Matthew James",
    "email": "Quacky2200@hotmail.com",
    "url": "https://github.com/Quacky2200"
  },
  "license": "CC0-1.0",
  "bugs": {
    "url": "https://github.com/Quacky2200/spotify-web-player-for-linux"
  },
  "homepage": "https://github.com/Quacky2200/spotify-web-player-for-linux",
  "devDependencies": {
    "electron": "1.4.2",
    "dbus": "^0.2.19",
    "freedesktop-notifications": "^1.2.2",
    "mpris-service": "^1.1.1"
  },
  "dependencies": {
    "auto-launch": "^4.0.0",
    "electron-cookies": "^1.1.0",
    "node-unofficialmxm": "git+https://github.com/Quacky2200/node-unofficialmxm.git",
    "request": "^2.74.0"
  }
}
```

dev
```
{
  "name": "spotifywebplayer",
  "description": "An Electron wrapper of Spotify Web Player to increase desktop integration for a stable Spotify Player for Linux replacement",
  "version": "1.0.25",
  "devDependencies": {
    "electron-builder":"^8.1.0",
    "electron": "1.4.2",
    "dbus": "^0.2.19",
    "freedesktop-notifications": "^1.2.2",
    "mpris-service": "^1.1.1"
  },
  "productName": "Spotify Web Player for Linux",
  "postinstall": "install-app-deps",
  "author": {
    "name": "Matthew James",
    "email": "Quacky2200@hotmail.com",
    "url": "https://github.com/Quacky2200"
  },
  "scripts": {
    "pack": "build --dir",
    "dist": "build"
  },
  "build": {
    "extraResources": "plugins/libpepflashplayer-${arch}.so",
    "linux": {
      "category": "Audio",
      "target":["AppImage", "deb"],
      "synopsis":"An Electron wrapper of Spotify Web Player to increase desktop integration for a stable Spotify Player for Linux replacement",
      "desktop":"[Desktop Entry]Name=Spotify Web Player\nComment=An Electron wrapper of Spotify Web Player to increase desktop integration for a stable Spotify Player for Linux replacement\nVersion=1.0.25\nExec=bash /usr/bin/$app/$app\nPath=/usr/bin/spotifywebplayer\nIcon=spotify\nCategories=GNOME;GTK;AudioVideo;Audio;Player;\n"
    }
  }
}
```

I'm not sure if the development dependencies are supposed to go in both or which. I use a basic plugin script that references the new plugin from `${__dirname}/plugins/libpepperflash-ia32.so` to `${__dirname}/../plugins/libpepperflash-ia32.so`

**Comment by develar** [comment] 2016-11-11 08:11
@Quacky2200 BTW, since electron-builder 8.x two-package.json structure is not required even if you have native deps.

**Comment by Quacky2200** [comment] 2016-11-11 08:13
Well the README I read it from said it was easier to have two even though you could have one, I just followed it because I thought it might be easier to follow the guide

**Comment by develar** [comment] 2016-11-11 08:22
@Quacky2200 Working on it, I will send PR soon.

**Comment by develar** [comment] 2016-11-11 10:55
https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/pull/49

**Comment by Quacky2200** [comment] 2016-11-11 14:30
Wow you guys are amazing, I looked at the pull request, I would have had no idea. I will test it in a bit but from what you have done in the PR, it looks like it'll be fine. I'm very excited to try this out 😄

**Comment by develar** [comment] 2016-11-11 14:32
> I will test it in a bit but from what you have done in the PR

I have tested — flash player is enabled, D-Bus is active and working. Well, I cannot listen radio due to number of connection refused errors but I don't know — probably due to my location / VM.

**Comment by Quacky2200** [comment] 2016-11-11 14:37
I know you wouldn't submit it without it working as there wouldn't be much point or much of a different, I still want to have a play though, I felt so frustrated at the time haha 😄 😆

**Comment by Quacky2200** [comment] 2016-11-11 14:52
Merged e3c308dc1cb24a5c85864023f88474e95ddbd8f0 👍

**Comment by Quacky2200** [comment] 2016-11-11 15:36
Ok I do have a small problem with this, I cannot get D-Bus to work, at first it couldn't find the service.js file upon inspection in DevTools, I looked into the code and changed used the same method that you used for removing app.asar, but instead to app.asar.unpacked in the controller for it to be able to start the D-Bus service but now it cannot find mpris-service, even though it's in the node_modules folder

Also I was just wondering, since I need a working version of node in this, either from my libs directory or from the users computer in `/usr/bin/node`, does node get packaged into the application? I can only assume it doesn't, we will need to make sure we have a local version running inside that AppImage since D-Bus has a few problems with libnode.so present in Electron itself.

**Comment by develar** [comment] 2016-11-11 15:51
> I looked into the code and changed used the same method that you used for removing app.asar

In this case you should use `asar.unpack` option. Do you mean file `services.js`? It is already unpacked but... I see that `mpris-service` is not unpacked... I will investigate.

> but now it cannot find mpris-service, even though it's in the node_modules folder

should be unpacked as well.

> I was just wondering, since I need a working version of node in this, either from my libs directory or from the users computer in /usr/bin/node, does node get packaged into the application

No. You 

Well... Ok, I can or only advice, or send PR :) I will send PR because I don't like `asar.unpack` (no other solution for now, but should be).

**Comment by Quacky2200** [comment] 2016-11-11 15:58
The file `services.js` cannot be found, that's in `controller.js` line ~66. I was thinking that since it relies on node, we could unpack the `libs/node` directory generated by `get_prerequisites.sh` so that we don't rely on a local node. Since mpris-service is not unpacked, we it be easier to use `npm install --legacy-bundling` to unpack only `mpris-service`, `freedesktop-notifications` and `dbus`/`dbus-native`?

**Comment by develar** [comment] 2016-11-11 16:01
> Since mpris-service is not unpacked, we it be easier to use npm install 

No, you just should need to set proper "asar.unpack" option. It is not easy and not intuitive — that's why I will send you PR and will fix this usability issue. (because this option belongs not to electron-builder, but to ASAR and we didn't yet fix it to make usable).

I will send you PR soon.

**Comment by develar** [comment] 2016-11-11 17:30
#51 addressed `unpack` (sorry, I haven't tested app, but should be ok).

> we could unpack the libs/node directory generated by get_prerequisites.sh

 `libs/node` should be added to `extraResources`.

I don't have time to prepare PR for that, so, just post conf:

```json
    "files": ["**/*", "!spotifywebplayer", "!*.md", "!*.sh", "!libs/electron"],
    "extraResources": ["plugins/libpepflashplayer-${arch}.so", "libs/node"],
```

Please note – I added `libs/electron` to excluded — for what it electron is required?

**Comment by Quacky2200** [comment] 2016-11-11 17:34
I just still have it included as part of my old dev setup that would manually make a workable installation, however, once this all works, that along with the make_deb.sh, and spotifywebplayer will be removed.

**Comment by probonopd** [comment] 2017-01-08 01:21
@Quacky2200 is something still blocking AppImage generation?

**Comment by Quacky2200** [comment] 2017-01-08 01:27
At the moment development is a bit slow, I will probably try again tomorrow as I have been finishing some dev. tonight. Last time I tried I still had issues with pepper flash, do you know if you still have these issues? I have tried copying everything that was done by @develar  but I still had problems each time.

**Comment by Quacky2200** [comment] 2017-01-08 08:43
Update: I think I have found out a fix for my node dependency. Since I need to use dbus and as far as I know, the dbus module is a native module...I think...Pretty sure it is since it relies on native bindings? I was thinking of including node as a node_module but that doesn't work and sounds pretty dumb (but sort of on the right track). What I think I actually need is to [rebuild electron to use native node modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) when I package it. I'm very new as to how npm will re-compile everything and I'm pretty sure it will take ages with each test. Would any of you know how to do this so that if this works, that I can be able to package it into deb and AppImage?

**Comment by develar** [comment] 2017-01-08 09:14
Electron-builder automatically rebuilds native node modules for you.

**Comment by Quacky2200** [comment] 2017-01-08 10:04
This is different though isn't it? When I'm rebuilding electron, can't I use the node-bindings rather than libnode bindings? I'm pretty sure that's the issue I'm facing since the current libnode bindings cannot be used with the dbus library without separately using node, maybe I'm confusing myself?

**Comment by Quacky2200** [comment] 2017-01-14 00:06
I was wondering if you @probonopd or @develar would be able to test my recent changes in my repo in a 32 bit environment? I have been successful with getting everything ready for AppImage generation on 64 bit but I keep getting an 'undefined symbol' from the dbus-library when running on 32-bit. Luckily 64 bit is fine right now. Also, how would I be able to build a 32 bit image on 64 bit when using `npm run dist`?

**Comment by Quacky2200** [comment] 2017-01-14 13:58
Hey guys, I was wondering how I could get my right-click unity menu back through the .desktop file? Is there some kind of attribute that would allow me to [add this on](https://gist.github.com/Quacky2200/bba7f767df4ccf124ce8c904d91e8528)?

**Comment by develar** [comment] 2017-01-14 14:04
@Quacky2200 You can add custom `[Desktop Entry]` https://github.com/electron-userland/electron-builder/issues/931#issuecomment-262806705 but not new entries. Could you please file issue?

**Comment by Quacky2200** [comment] 2017-01-14 14:12
Ok I have made the issue, sorry about the constant editing. I pressed enter by mistake o.0

**Comment by Quacky2200** [comment] 2017-01-14 15:04
I have tried building 32 bit snaps but I get an error, are 32 bit snaps supported? I'm quite unsure what this means and if I should make another issue on electron-builder? I'm willing to skip 32 bit snaps for now but still want to see what my problem is :smile: 
![screenshot from 2017-01-14 15-02-18](https://cloud.githubusercontent.com/assets/4623599/21955832/abe23794-da6a-11e6-8352-574826b648f0.png)

**Comment by develar** [comment] 2017-01-14 15:30
Snaps multi arch feature is experimental and not all plugins are updated — you can file/file issue to snapcraf. So, for now, it seems you need to build snaps on 32 bit machine.

**Comment by Quacky2200** [comment] 2017-01-14 16:44
Ahh it worked, thanks :+1:

**Comment by Quacky2200** [comment] 2017-01-14 19:26
I'm closing this as the packaging has been improved :smile:

**Closed by Quacky2200** 2017-01-14 19:26 UTC
Labels: enhancement
